Repository dnanexus/dxCompiler, pull requests merged in 2022-08, with the labels that each got.

#359 APPS-1305 fix stage params mapping
  RELEASE_NOTES.md
  compiler/src/main/scala/dx/translator/cwl/ProcessTranslator.scala
Labels: cwl_conformance

#356 APPS-1281 fix cwl types casting between scatters
  RELEASE_NOTES.md
  compiler/src/main/scala/dx/translator/cwl/ProcessTranslator.scala
  core/src/main/scala/dx/core/languages/cwl/CwlBlock.scala
  executorCwl/src/main/scala/dx/executor/cwl/CwlWorkflowExecutor.scala
Labels: cwl_conformance

#367 APPS-1308 dxCompiler Post release 2.10.3
  RELEASE_NOTES.md
  build.sbt
  compiler/src/main/resources/application.conf
  core/src/main/resources/application.conf
  executorCommon/src/main/resources/application.conf
  executorCwl/src/main/resources/application.conf
  executorWdl/src/main/resources/application.conf
Labels: minor

#362 APPS-1269 APPS-1270 Update manifest out unqualified file
  RELEASE_NOTES.md
  build.sbt
  compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
  compiler/src/test/resources/bugs/apps-788.wdl
  compiler/src/test/resources/manifest/apps_1269_1270_unqualified_ids_manifest_unit.wdl
  compiler/src/test/resources/manifest/apps_1269_1270_unqualified_ids_manifest_unit_input.json
  compiler/src/test/scala/dx/compiler/CompilerTest.scala
  scripts/run_tests.py
  test/manifest/apps_1269_1270_unqualified_ids_manifest.wdl
  test/manifest/apps_1269_1270_unqualified_ids_manifest_input.json
Labels: integration, cwl_conformance

#368 APPS-1309 Update input and output specs manifest
  doc/ExpertOptions.md
Labels: documentation, minor

#321 APPS-1081 fix override docker requirement
  RELEASE_NOTES.md
  build.sbt
  compiler/src/main/scala/dx/translator/InputTranslator.scala
  compiler/src/main/scala/dx/translator/cwl/CwlTranslator.scala
  executorCwl/src/main/scala/dx/executor/cwl/CwlTaskExecutor.scala
Labels: integration, cwl_conformance

#370 APPS-1354 Fix release notes
  RELEASE_NOTES.md
Labels: documentation, minor

#371 APPS-1319 Update add CWL conformance test batch
  README.md
Labels: documentation, minor

#373 APPS-1319 cwl conformance badge - REVERT
  README.md
Labels: documentation, minor

#374 APPS-1318 Update undeclared output of StdLib func
  build.sbt
  scripts/run_tests.py
  test/wdl_1_0/apps_1318_nested.wdl
Labels: integration

#377 Dxcint error message
  dxcint/dxcint/utils.py
  executorCommon/src/main/scala/dx/executor/WorkflowExecutor.scala
Labels: minor
