Repository dnanexus/dxCompiler, pull requests merged in 2022-04, with the labels that each got.

#329 APPS-1169 fix ignore reuse precedence
  compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
  compiler/src/test/resources/subworkflows/check_route.wdl
  compiler/src/test/scala/dx/compiler/CompilerTest.scala
  test/cwl_cromwell/cwls/cwl_scatter-wf1.cwl
  test/cwl_cromwell/cwls/cwl_scatter-wf1.cwl.json
  test/cwl_cromwell/cwls/cwl_scatter-wf1_input.yaml
  test/special_flags/add2_extras.json
Labels: cwl_conformance

#325 APPS-1032 delay workspace destruction
  RELEASE_NOTES.md
  compiler/src/main/scala/dx/translator/Extras.scala
  compiler/src/main/scala/dxCompiler/Main.scala
  doc/ExpertOptions.md
Labels: minor

#326 APPS-1124 restrict applet network access
  RELEASE_NOTES.md
  compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
  compiler/src/main/scala/dx/translator/cwl/ProcessTranslator.scala
  compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala
  compiler/src/test/resources/compiler/extras/short_timeout.json
  compiler/src/test/resources/compiler/extras/task_specific_short_timeout.json
  compiler/src/test/scala/dx/compiler/CompilerTest.scala
Labels: integration, cwl_conformance

#331 APPS-1149 update wdlTools dependency
  RELEASE_NOTES.md
Labels: integration, cwl_conformance

#332 APPS-1176 Update notes before the next release
  RELEASE_NOTES.md
  doc/ExpertOptions.md
Labels: minor

#334 APPS-1124 revert PR326
  build.sbt
  compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
  compiler/src/main/scala/dx/translator/cwl/ProcessTranslator.scala
  compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala
Labels: integration, cwl_conformance

#337 APPS-1181 Run customer tests without asking for confirmation
  scripts/run_customer_tests.sh
Labels: minor
