Repository dnanexus/dxCompiler, pull requests merged in 2022-07, with the labels that each got.

#354 APPS-1271 Update improve manifest docs
  doc/ExpertOptions.md
Labels: documentation, minor

#357 APPS-1210 duplicate process ID
  build.sbt
  core/src/main/scala/dx/core/languages/cwl/CwlBundle.scala
  executorCwl/src/main/scala/dx/executor/cwl/CwlWorkflowExecutor.scala
  scripts/bundled_dependencies.json
Labels: cwl_conformance

#365 APPS-1321 Update openjdk to 11
  scripts/util.py
Labels: integration, cwl_conformance
